export BUILT_PRODUCTS_DIR="/Users/ahmedalmoraly/Library/Developer/Xcode/DerivedData/ParseSync-bftnlvjxhdobsbfroihmtgxlbeil/Build/Products/Debug-iphonesimulator"
export CURRENT_ARCH="x86_64"
export OBJECT_FILE_DIR_normal="/Users/ahmedalmoraly/Library/Developer/Xcode/DerivedData/ParseSync-bftnlvjxhdobsbfroihmtgxlbeil/Build/Intermediates/ParseSync.build/Debug-iphonesimulator/ParseSyncTests.build/Objects-normal"
export OBJROOT="/Users/ahmedalmoraly/Library/Developer/Xcode/DerivedData/ParseSync-bftnlvjxhdobsbfroihmtgxlbeil/Build/Intermediates"
export SRCROOT="/Users/ahmedalmoraly/Developer/RMParseSync/ParseSync"
